"use client";

import { useTitleData } from "@/components/title-provider";
import Link from "next/link";
import { Button } from "./ui/button";
import {
	Tooltip,
	TooltipContent,
	TooltipProvider,
	TooltipTrigger,
} from "./ui/tooltip";

export function ContentHeader() {
	const { titleData } = useTitleData();
	const { title, UGC, icon } = titleData;

	return (
		<header className="flex w-full flex-row justify-between border-sidebar-border/75 border-b p-2">
			<h1 className="font-bold text-2xl md:text-5xl">
				{icon && (
					<img
						src={icon}
						alt={title}
						className="inline-flex h-6 w-auto rounded-full md:h-12"
					/>
				)}
				{title}
			</h1>
			{UGC && (
				<TooltipProvider>
					<Tooltip>
						<TooltipTrigger>
							<Button variant="destructive" size="sm" aria-disabled>
								UGC
							</Button>
						</TooltipTrigger>
						<TooltipContent className="w-full max-w-sm">
							<p className="text-pretty">
								This content is generated by a user and is not a main wiki page.
								Do not take any of the information on this page as gospel. The
								BCUW is not responsible for any misinformation on this page. Any
								harmful or illegal content may be reported by emailing{" "}
								<Link
									href="mailto:contact@email.bcuw.xyz?subject=Harmful%20or%20illegal%20content%20Report"
									className="text-pink-500 underline"
								>
									contact@email.bcuw.xyz
								</Link>{" "}
								or contacting @Altie122 on Discord.
							</p>
						</TooltipContent>
					</Tooltip>
				</TooltipProvider>
			)}
		</header>
	);
}
